#!/bin/sh

mkdir -p /usr/share/daed

[ -e /usr/share/v2ray/geoip.dat ] && ln -sfn /usr/share/v2ray/geoip.dat /usr/share/daed/geoip.dat
[ -e /usr/share/v2ray/geosite.dat ] && ln -sfn /usr/share/v2ray/geosite.dat /usr/share/daed/geosite.dat

exit 0
